### ISSUE TITLE
Issue about project.new(fldr)

### ISSUE THREAD

**Issue by marcolee19970823** [AequilibraE/aequilibrae#338] opened 2022-09-10 02:47 UTC
Hi! I came across issues when the program encounter "project.new(fldr)".
As you can see from the below picture. 
![image](https://user-images.githubusercontent.com/47074370/189465841-cdad0df3-88a9-46b6-84ba-2d4c15a925c3.png)
![image](https://user-images.githubusercontent.com/47074370/189465973-4298eb05-dc8c-4669-8749-b1f15f43395e.png)

My python is 3.8. I installed AequilibraE 7.4, and I also installed openmatrix and spatialite.

Here is how I install spatialite:
![image](https://user-images.githubusercontent.com/47074370/189465920-cdbba9d5-a385-46e5-bea7-f7633b2e0cd2.png)

I just have no idea how to solve this problem. I cannot do anything further without addressing this issue. 
Is there anything wrong with installation? Thank you in advance for your solution and help!

**Comment by pedrocamargo** [comment] 2022-09-11 01:44
This is a question about spatialite, and NOT a bug with AequilibraE, so I am closing.

You can reach out to the AequilibraE mailing list (aequilibrae@googlegroups.com) for help

**Closed by pedrocamargo** 2022-09-11 01:44 UTC
Labels: question
