### ISSUE TITLE
Desire Line "Zone or Node Layer" drop down 

### ISSUE THREAD

**Issue by bgruswitz** [AequilibraE/aequilibrae#49] opened 2019-01-04 02:46 UTC
![desirelinetoolbox](https://user-images.githubusercontent.com/27835348/50671544-92960500-0fa0-11e9-82e7-69752ec9923d.png)

No layers show up in Desire Line Toolbox window dropdown for "Zone or Node Layer". I've tried having an ID field in multiple formats (float, text, integer, double) to see if it wants to IDs in a specific field type, but the dropdown remains blank and doesn't drop down.

**Comment by pedrocamargo** [comment] 2019-01-04 02:49
Hey Ben, 
              This might have something to do with the layer itself. Are you sure it is a polygon or point layer (and not multi-polygon or Multi-Point)?  TAZ layers are usually Multi-Polygon, and that does not work by design (centroids are ill-defined).

**Comment by bgruswitz** [comment] 2019-01-04 02:52
Pedro, thanks for the quick reply. It's a layer of census tracts, which could have the same issue. If I convert to centroid point layer, well this resolve the issue? I haven't had this issue in the past (QGIS 2 version).

**Comment by bgruswitz** [comment] 2019-01-04 03:35
Creating the centroid point layer seemed to do the trick. Thanks again, Pedro! Happy New Year, and congrats on the update!

**Comment by pedrocamargo** [comment] 2019-01-04 06:34
I am closing this, Ben.  An din the future, please log tghe issues regarding the QGIS interface here:
https://github.com/AequilibraE/AequilibraE-GUI

**Closed by pedrocamargo** 2019-01-04 06:34 UTC
